error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Traceback (most recent call last):
  File "/home/rpi/weatherhat-python/ICT-projecten/Programma/pyweatherfinale.py", line 148, in <module>
    background = pygame.image.load("icons/backgroundwm.png")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file 'icons/backgroundwm.png' found in working directory '/home/rpi/weatherhat-python/ICT-projecten/Programma'.
