error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Traceback (most recent call last):
  File "/home/rpi/weatherhat-python/ICT-projecten/Programma/pyweatherfinale.py", line 148, in <module>
    background = pygame.image.load("icons/backgroundwm.png")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file 'icons/backgroundwm.png' found in working directory '/home/rpi/weatherhat-python/ICT-projecten/Programma'.
To github.com:JohnaaQS/windmeter2.0.git
   a99a04c..28ab114  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   28ab114..5878eae  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   5878eae..1fb7add  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   1fb7add..893b6b7  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   893b6b7..cb7153a  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   cb7153a..04f0d60  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   04f0d60..a8d6529  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   a8d6529..2c276d5  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   2c276d5..66ef59b  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   66ef59b..00ab81b  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   00ab81b..023016a  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   023016a..faee952  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   faee952..91af7b2  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   91af7b2..f1dcfae  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   f1dcfae..da4815f  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   da4815f..da9bbe9  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   da9bbe9..0fd43cb  main -> main
To github.com:JohnaaQS/windmeter2.0.git
   0fd43cb..610353f  main -> main
